name: Build and Release WireWatch

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.x'
      
      - name: Install GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11 

      - name: Create buil dir
        run: mkdir -p build
      
      - name: Build
        run: |
          export CC=gcc-11
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          
      - name: Check for built executable
        run: ls -l ./build/wiwa

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/wiwa
          asset_name: wirewatch-linux
          asset_content_type: application/octet-stream